name: ChunkPreGenerator
author: lHawk_
version: 0.2
main: me.chunkpregenerator.Core
description: Pré-gera chunks no seu mundo com eficiência.
api-version: 1.13
load: STARTUP
folia-supported: true
commands:
  chunkpregenerator:
    description: Comando principal para pré-geração de chunks.
    usage: /<command>
