name: ChunkPreGenerator
author: lHawk_
version: 0.1
main: me.chunkpregenerator.Core
description: Pré-gera chunks no seu mundo com eficiência.
api-version: 1.13 # Compatível com 1.8.9, mas especificado para evitar warnings
load: STARTUP
commands:
    chunkpregenerator: